### PR TITLE
Update FAQ-context.md

### PR DESCRIPTION
**Pull request by ousia**
more accurate descriptions

### CODE REVIEW

**Comment by davidcarlisle** [comment]
The file is not that big so reviewing isn't impossibly difficult but since there are a few hundred of these files and we don't know how many update requests we will get, it would be good if we could set some guidelines to make reviewing easier.

Here you seem to have re-flowed all the text so the diff basically shows the entire file changed even though I think there are relatively few actual changes. A change that just changed the text without reflowing the rest of the document would be much easier to review.

**Comment by davidcarlisle** [comment]
without the reflowing the diff is

```
$ diff FAQ-context.md FAQ-context2.md
9c9,10
< created by Hans Hagen of Pragma-Ade; it started as a production tool
---
> created by Hans Hagen of Pragma ADE (which stands for
> Advanced Document Engineering); it started as a production tool
30c31
< extension `mkii`) which runs on pdfTeX but is not under
---
> extension `.mkii`) which runs on pdfTeX but is not under
32c33
< `mkiv`) (which runs on LuaTeX and is where development
---
> `.mkiv`) (which runs on LuaTeX and is where development
39,42c40,44
< [mailing list](https://mailman.ntg.nl/mailman/listinfo/ntg-ConTeXt).
< A "standalone" distribution (a TeX distribution with no macros
< other than ConTeXt-based ones) is available as the ["ConTeXt
< minimals"](http://minimals.contextgarden.net/) &mdash; it provides
---
> [mailing list](https://mailman.ntg.nl/mailman/listinfo/ntg-context).
> A "standalone" distribution (a TeX distribution with no macros other than
> ConTeXt-based ones) is available as ["ConTeXt
> Standalone"](http://wiki.contextgarden.net/ConTeXt_Standalone) (also
> known as "ConTeXt Minimals" or the "ConTeXt Suite") &mdash; it provides
44c46
< mark&nbsp;ii or mark&nbsp;iv ConTeXt.
---
> Mark&nbsp;II or Mark&nbsp;IV ConTeXt.
```


The change to use the `ConTeXt_Standalone` URL looks good thanks, Looking at other files I think we (mostly) refer to extensions as `tex`, `sty` etc rather than `.tex`, `.sty` so probably I'd leave the `mkii` reference.

**Comment by davidcarlisle** [comment]
Thanks If you'd like to add your name to the AUTHORS.md let us know what to put (you could do that by mail if you don't want direct association with your real name and github id)

**Comment by ousia** [comment]
@davidcarlisle, sorry for the reflowing. I wanted to do that myself, but yesterday wasn’t the day.

Being the modification minimal (even if I wanted, I couldn’t claim any copyright on this), I’m surprised that both author and pull request number are referenced in the changelog.

**Comment by ousia** [comment]
Closing the pull request myself.

**Pull request closed without merging**
