### PR TITLE
Stop links turning bold on focus

### PR DESCRIPTION
**Pull request by moewew**
This makes links behave the same on hover and focus.

### CODE REVIEW

**Comment by moewew** [comment]
Oh, sorry. I just realised this pull request also includes my changes to `Q-capbibtex`. Feel free to close the pull request in case you only want to merge the links turning bold.

**Comment by davidcarlisle** [comment]
yes two PRs would have been better, I can add the focus css by hand thanks,
do you want the change to capbibtex to be considered now, or were you still
working on it and didn't mean to submit yet?

**Comment by davidcarlisle** [comment]
I've done the CSS, thanks, I'll let @josephwright  to review bib*tex things...

**Comment by moewew** [comment]
Sorry, I forgot about that. Should be done now - hopefully correctly.

**Pull request merged**
